### ISSUE TITLE
Add `Validation` data type to Extra modules

### ISSUE THREAD

**Issue by vrom911** [kowainik/relude#100]
It's not in `base`, but in `either` package:

* https://hackage.haskell.org/package/either-5.0.1/docs/Data-Either-Validation.html#t:Validation

Though you don't usually want to drag all that dependencies, so maybe it makes sense to reimplement it in some `Extra` module?

**Comment by ChShersh** [comment]
@vrom911 Completely agree with this 👍 💯 You probably don't want to depend on `either` package in lightweight libraries or applications. But `Validation` data type is extremely useful. And since we have `Extra` modules, it's relatively easy to add known and common things to the `relude` without worrying about name clashes.

**Comment by kahlil29** [comment]
Would this include a reimplementation of `Validation` with new enhancements/features or we would just reuse the current data declaration and instances from `Data.Either` ?

**Comment by ChShersh** [comment]
@kahlil29 Couple hours ago I've received an unexpected email from @mauriciofierrom with the attempt to resolve this issue. Here is the gist:

* https://gist.github.com/mauriciofierrom/bdb7a5d0ff06c4a23b51ef7bfa7d81d9

I will duplicate my comments to this solution here:

1. You can also add Bifoldable and Bitraversable instances. These typeclasses are already in base and we're going to reexport them as well. See relevant issues:
* https://github.com/kowainik/relude/issues/98
* https://github.com/kowainik/relude/issues/99
2. It would be really nice to use `-XInstanceSigs` extension and all type signatures to all methods in all instances. In `relude` we want our package to be as beginner-friendly as possible, and having such type signatures significantly increases code readability. See example in this module:
* https://github.com/kowainik/relude/blob/master/src/Relude/Extra/Foldable1.hs
3. Also, usually, when you're writing general purpose library, it's a good idea to implement all methods from the typeclasses. Default implementations might not be efficient.
4. In addition to previous point: adding `{-# INLINE #-}` pragma to every implemented method helps performance as well.
5. Also, in `relude` we're using 4 spaces for indentation :)

**Comment by mauriciofierrom** [comment]
@ChShersh thanks for the comments. If it's ok with you (and @kahlil29) I will work on this issue then.

**Comment by kahlil29** [comment]
@ChShersh Noted :) 
 @mauriciofierrom Go ahead 👍
