### ISSUE TITLE
[RFC] Add `zipWith const` or `zipWith (flip const)` function

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#126]
Inspired by this blog post:

* https://github.com/quchen/articles/blob/master/2018-11-22_zipWith_const.md

And this comment:

* https://www.reddit.com/r/haskell/comments/9zf1tj/zipwith_const_is_my_favorite_haskell_function/ea90fqs/

The name of the function is under the question though...

**Comment by cronokirby** [comment]
Maybe `zipLeft`?

**Comment by ChShersh** [comment]
@cronokirby Hmm :thinking: I think I might forget the meaning of `Left` each time I look at this function: does `Left` stands for taking elements from left list or does `Left` means that it takes element according to left list?

**Comment by tysonzero** [comment]
`ZipList` already makes this nice via `<*` and `*>`, I would suggest instead making `ZipList` as nice to use as `[]`.

**Comment by chshersh** [comment]
I had the impression that this function is useful. But I haven't used since creating this issue. Also, this function is not that performant since it traverses the list prefix twice. So I propose to not add rarely used and non-optimal functions to the prelude package.
