### ISSUE TITLE
Should relude export `mask`, `onException`, `finally`?

### ISSUE THREAD

**Issue by TomMD** [kowainik/relude#143]
`mask` and friends are key to writing good exception safe code.  Its absence from relude entirely could be easily, and without disturbance, be rectified with a `Relude.Extra.Exception` module.  Agreed? What about exporting these operations by default from `Relude`?

**Comment by ChShersh** [comment]
@TomMD I agree that these functions are useful. But one goal of the `relude` is not give any preferences to competing abstractions in the ecosystem, giving users the most freedom.

> 4. **Minimalism** (low number of dependencies). We don't force users of `relude` to stick to some specific lens or text formatting or logging library.

Regarding functions like `mask`: there are several libraries that export this function under different types:

* `base` — `mask :: ((forall a . IO a -> IO a) -> IO b) -> IO b`
* `exceptions` — `mask :: MonadMask m => ((forall a . m a -> m a) -> m b) -> m b`
* `lifted-base` — `mask :: MonadBaseControl IO m => ((forall a . m a -> m a) -> m b) -> m b`
* `unliftio` — `mask :: MonadUnliftIO m => ((forall a . m a -> m a) -> m b) -> m b`

Sticking to one option will conflict with intentions of other users. They will need to hide this function and export from another library. Also, reexporting `mask` from any other place than `base` will introduce new dependencies.

**Comment by TomMD** [comment]
I see.   Thanks for the clarification.
