### ISSUE TITLE
Left-associative, short-circuiting fold

### ISSUE THREAD

**Issue by josephcsible** [kowainik/relude#155]
I think adding a method like this might be useful:
```haskell
foldlSC :: Foldable t => (b -> a -> Either b b) -> b -> t a -> b
foldlSC f z = either id id . foldlM f z
```
It allows easy implementation of a fold that's both left-associative and short-circuiting. If `f` returns `Left l`, then the fold short-circuits with `l` as the answer. If `f` returns `Right r`, then the fold continues as usual with `r` as the new accumulator. Example of its use:
```haskell
myProduct :: (Foldable t, Eq a, Num a) => t a -> a
myProduct = foldlSC go 1
  where go _ 0 = Left 0
        go acc x = Right $! acc * x
```
Using this kind of fold gives `myProduct` two desirable properties: `myProduct (0:undefined)` returns 0, and `myProduct (replicate 10000000 1)` runs in constant space.

**Comment by ChShersh** [comment]
@josephcsible Thanks for this proposal! I don't mind having short-circuiting folding function in the `relude`. Probably in some extra module. And, also, I wouldn't use `foldlM` from `base`, the implementation looks not sufficiently efficient, and we can do better here.

**Comment by josephcsible** [comment]
How about like this?
```haskell
foldlSC :: Foldable t => (b -> a -> Either b b) -> b -> t a -> b
foldlSC f = flip $ foldr go id
  where go x z acc = either id z $ f acc x
```

I'm also going to add a `'` (strict) variant and a `flipfoldlSC` variant.

**Comment by ChShersh** [comment]
@josephcsible It's not that easy to follow your definition. But it looks like it will expand into the following using the equational reasoning technique:

```haskell
foldlSC f b [1,2,3]
= flip (foldr go id) b [1,2,3]
= foldr go id [1,2,3] b
= (go 1 $ go 2 $ go 3 $ go id) b
= (either id (go 2 $ go 3 $ go id) . flip f 1) b
....
```

What I would like to avoid is having to keep whole stack of evaluation for the complete `Foldable` object. It's not clear to me that this happens with this definition. So I was thinking about more explicit implementation using local `go` function so the behavior is obvious from looking at the code.

**Comment by josephcsible** [comment]
> What I would like to avoid is having to keep whole stack of evaluation for the complete Foldable object. It's not clear to me that this happens with this definition.

Does `myProduct` running in constant space not demonstrate that this happens?

> more explicit implementation using local `go` function

I'm not sure what you mean by this. Do you mean explicit recursion instead of `foldr`? Wouldn't that mean that this would only work for lists and not for anything `Foldable`?

**Comment by ChShersh** [comment]
@josephcsible Oh, I see. Yeah, makes sense to go with the `foldr` implementation. However, personally, I would implement local `go` function explicitly making the intention clearer:

```haskell
foldlSC :: Foldable t => (b -> a -> Either b b) -> b -> t a -> b
foldlSC f = flip $ foldr go id
  where
    go :: ???
    go ... = case f x of ...
```

**Comment by josephcsible** [comment]
How's this for `go`?

```haskell
go :: a -> (b -> b) -> b -> b
go x z acc = case f acc x of
 Left l -> l
 Right r -> z r
```

(I wrote this on my phone, so it's untested. Once I get back to a computer, if it looks good, I'll PR it.)

**Comment by ChShersh** [comment]
@josephcsible This looks good!

**Comment by josephcsible** [comment]
#157
