### ISSUE TITLE
Implement common type-families in the `Relude.Extra.Types` module

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#156]
Sometimes they are needed for different tasks. Maybe we can put some of the into our `relude` to ease various tasks. I can think of the following useful type families:

- [ ] `type family (++) (xs :: [k]) (ys :: [k]) :: [k]`
- [ ] `type family All (f :: k -> Constraint) (xs :: [k]) :: Constraint`
- [ ] `Fst/Snd` to get first second elements of different tuples

This is something I can think of now. Maybe more useful functions/operators can be added later.

**Comment by TheMatten** [comment]
```haskell
type (f :: k -> k') $ (a :: k) = f a
```
would be nice to have too - but question is, what precedence should it have - 0 to be completely equivalent to term level operator, or 1 to allow making arguments with parens more pleasant?:
```haskell
:: Foo (Bar a b (Baz c)) -> FooBar
```
could be written as:
```haskell
:: Foo $ Bar a b $ Baz c -> FooBar
```
(This is what I personally use in my Relude wrapper)

**Comment by TheMatten** [comment]
Type level composition probably won't be really useful with saturation restriction, even less if we could have `($)` (you probably don't want to introduce defunctonalization from `singletons`, do you? :smile:)

**Comment by chshersh** [comment]
@TheMatten type-level `($)` operator is defined in the `type-operators` package:

* http://hackage.haskell.org/package/type-operators

`relude` previously had this package in its dependencies but dropped it to have smaller dependencies footprint. I used this operator and it was lovely; however it caused troubles with tooling and made some of them fail. Also, code that uses `($)` operator on a type-level is harder for beginners to read. Unlike operators like `(++)` which don't have alternatives on a type-level. And `All` is just nice 🙂 

I agree that type level composition is not that useful currently, so I'm dropping it from the list. Btw, some inspiration for functions can be found in the following package:
* https://github.com/kcsongor/typelevel-prelude

**Comment by TheMatten** [comment]
> type-level ($) operator is defined in the type-operators package

Thanks for pointing out! Hmm, but some of the operators here really seem a little bit like an overkill, completely destroying readability...

> I used this operator and it was lovely; however it caused troubles with tooling and made some of them fail. Also, code that uses ($) operator on a type-level is harder for beginners to read.

Okay, seems reasonable :slightly_smiling_face:

Wow, didn't know @kcsongor is actually working on unsaturated type families, can't wait! :smile:

I could make a PR - are there some other operators that would be interesting? :smile:

**Comment by TheMatten** [comment]
There's already `All` newtype from `base` - should type family be renamed or just imported qualified?

**Comment by chshersh** [comment]
@TheMatten Hmm... `All` is indeed defined in `base` and actually reexported by `relude` by default so having type family with name `All` will cause inconvenience. In that case, I can say that having only `(++)` type level operator is safe. If we want to have something like `All`, we need to come up with a better name.

I would gladly accept the PR that just adds `(++)`! Looks like now we can't introduce too much new custom functions.

**Comment by TheMatten** [comment]
We can consider something like `AllHave` or just `Have` (- instance), but it's not critically important, so I don't mind dropping this for now :smile: 

Ok, will do :slightly_smiling_face:

`Fst` and `Snd` can be implemented so that they work on both promoted tuples and tuple types - question is, if they're useful enough in current setting - should I add them to PR?
