### ISSUE TITLE
Add AppVeyor CI

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#160]
Current settings for Appveyor are quite fast. And it might be useful to have Windows CI check for a standard library.

**Comment by Arkham** [comment]
Taking a stab at this :)

**Comment by chshersh** [comment]
@Arkham Thanks for that! You may find the following blog post useful :slightly_smiling_face: It describes the easiest way to install Haskell on Windows and also has AppVeyor example. But we probably will need to polish the example a little bit...

* https://hub.zhox.com/posts/introducing-haskell-dev/

**Comment by Arkham** [comment]
Thanks @chshersh, I've managed to find a couple of `appveyor.yml` from other haskell projects, and managed to get [a build](https://ci.appveyor.com/project/JuLiu/relude/builds/27943254) to pass 🎉
