### ISSUE TITLE
Implement `Elem` type family

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#170]
I found myself implementing it almost every time when using custom type errors. Probably a good idea to add it to the `Extra.Type` module :slightly_smiling_face:

**Comment by Cmdv** [comment]
@chshersh can you give an example of what `Elem` would look like?: tried looking for an example on stackage but it wasn't error related. 😄

**Comment by chshersh** [comment]
@Cmdv Basically it would be nice to have something like this type family from `servant`: simple type-level `elem` with custom type errors.

* https://hackage.haskell.org/package/servant-0.16.2/docs/Servant-API-TypeLevel.html#t:Elem

**Comment by kutyel** [comment]
Is this done already? 🙂

**Comment by vrom911** [comment]
@kutyel , I know for sure that @Cmdv was working at this. Let's check with him if he would like to proceed with that :slightly_smiling_face: 
@Cmdv , could you confirm that you still wish to work on that?

**Comment by Cmdv** [comment]
@kutyel @vrom911 ahh no I've not had time! feel free to take it over, but before you do check out this comment in the original PR I submitted https://github.com/kowainik/relude/pull/188#discussion_r326142498 🙂
