### ISSUE TITLE
Add useful `Semigroup` and `Monoid` instances for `Validation`

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#172]
Currently our `Validation` doesn't have `Semigroup` and `Monoid` instances. It would be a great idea to add them. And also write better documentation for the `Validation` module with use cases 🙂 I also noticed that we have our own implementation of `liftA2` but it's inefficient compared to `<*>` so it's better just to remove it.

```haskell
instance (Semigroup e, Semigroup a) => Semigroup (Validation e a) where
    x <> y = liftA2 (<>) x y

instance (Semigroup e, Monoid a) => Monoid (Validation e a) where
    mempty = Success mempty
```

**Comment by mauriciofierrom** [comment]
Hello! I've opened a PR to address this. Could you please elaborate on 
> And also write better documentation for the Validation module with use cases
With examples maybe? I would like to try and help with that too :slightly_smiling_face:
