### ISSUE TITLE
Generalise `mapBoth` to `Bifunctor`

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#174]
Currently we have the following `mapBoth` function in the `Relude.Extra.Tuple` module:

https://github.com/kowainik/relude/blob/31ad83485e2a83c607669bd2e7a73d33209404f3/src/Relude/Extra/Tuple.hs#L64-L65

I propose to generalise the type signature of this function so it can work with any `Bifunctor`:

```haskell
mapBoth :: Bifunctor f => (a -> b) -> f a a -> f b b
```

For this we need:

* Move `mapBoth` to `Relude.Extra.Bifunctor`
* Generalise and implement
* Add more examples to the documentation

**Comment by chshersh** [comment]
Instead of moving, let's introduce `bimapBoth` function and deprecate `mapBoth` first.

**Comment by josephcsible** [comment]
Should we do `traverseBoth` -> `bitraverseBoth` and generalize/move it too?

**Comment by chshersh** [comment]
@josephcsible I'm not sure about `bitraverseBoth`. I would like to keep `relude` minimal and not introduce rarely used combinators. I needed `mapBoth` enough times to be included in `Extra` modules but I never needed `bitraverseBoth`

**Comment by josephcsible** [comment]
We already have `traverseBoth` though, so we'd just be generalizing it, not adding a new one.

**Comment by chshersh** [comment]
@josephcsible This involves solving several awkward problems:

1. Deprecation cycle for `traverseBoth` should be done as well.
2. `bitraverse` is for `Bitraversable` while the module is called `Bifunctor`. It feels awkward to put `Bitraversable` function into a module called `Bifunctor`. And introduce module with the name `Bitraversable` looks like a heavy solution for generalising one rarely used function. I would love to have fewer modules, not more :slightly_smiling_face:

**Comment by astynax** [comment]
I can take this one, but what I'll need to do specifically? :)

> Instead of moving, let's introduce bimapBoth function and deprecate mapBoth first.
Just this part?

**Comment by chshersh** [comment]
@astynax Yep, only this part. Specifically:

1. Implement `bimapBoth` in the `Relude.Extra.Bifunctor` module
2. Add `{-# DEPRECATE #-}` pragma to `mapBoth`
3. Move documentation from `mapBoth` to `bimapBoth` and add couple extra usage examples using `doctest (they will be very helpful!)
