### ISSUE TITLE
Implement property-based tests for `Validation`

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#176]
Most important instances that need to be covered:

1. Applicative
2. Alternative
3. Semigroup
4. Monoid

Also, I've noticed that `*>` and `<*` operators are not implemented efficiently, they need to implemented in the style of `<*>`... So once we have tests we can verify that the implementations are indeed correct.

**Comment by astynax** [comment]
Can I take this one?

**Comment by chshersh** [comment]
@astynax Sure, go for it!

**Comment by chshersh** [comment]
@astynax hi, friendly ping :slightly_smiling_face: How are you doing? Are you stuck on anything? Feel free to ask any questions or clarify any details :slightly_smiling_face:

**Comment by astynax** [comment]
Friendly pong! I'm still playing with Hedgehog, but I'm thinking that I almost grok it :)

**Comment by astynax** [comment]
Sorry for delay, I was pretty sick for more than week :(

**Comment by astynax** [comment]
I think I'm done ([PR](https://github.com/kowainik/relude/pull/216)). Or it will be good to check anything else? :)

**Comment by chshersh** [comment]
@astynax Thanks for the work! I will try to review as soon as I can and comment on the PR :slightly_smiling_face:
