### ISSUE TITLE
Remove `tasty*` dependencies

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#187]
We're using plain `hedgehog` to implement property-based tests. So it's enough to use only `hedgehog` and decrease dependency footprint for the `relude` package. This should speed up building of the package and decrease maintenance burden.

**Comment by sshine** [comment]
Question: When a test suite depends on something, does this propagate to the dependency list of the package in total? I actually thought there was some way to keep the tests in a Hackage package and yet not let them influence dependencies. I guess I was wrong.

**Comment by sshine** [comment]
OK, so it's strictly build times and maintenance that Dmitrii talks of. Thanks. :)
