### ISSUE TITLE
Add `guarded` combinator

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#203]
After some time I find myself needing it several times. So let's return it back. Apparently, it's occasionally useful

This combinator has the following type:

```haskell
guarded :: Alternative f => (a -> Bool) -> a -> f a
```

**Comment by JonathanLorimer** [comment]
I would like to take a run at this, although I am not sure where it should live? Should I make a new file `Alternative.hs`?

**Comment by vrom911** [comment]
Thanks for taking this @JonathanLorimer !
I would expect it in the [`Relude.Bool.Guard`](https://github.com/kowainik/relude/blob/master/src/Relude/Bool/Guard.hs) module. @chshersh, could you please confirm that you had the same place in mind?

**Comment by chshersh** [comment]
@vrom911 you're absolutely right. It should go to the `Relude.Bool.Guard` module
