### ISSUE TITLE
Add `mapMaybeM`

### ISSUE THREAD

**Issue by vrom911** [kowainik/relude#214]
With the type

```haskell
mapMaybeM :: (a -> m (Maybe b)) -> f a -> m (f b)
```

**Comment by josephcsible** [comment]
That looks exactly like [`wither`](https://hackage.haskell.org/package/witherable-0.3.4/docs/Data-Witherable.html#v:wither). How do you plan to implement it without the `Filterable` or `Witherable` typeclasses?

**Comment by chshersh** [comment]
@josephcsible Specialization to `[]` should work for now :+1: And once something like `Witherable` gets into `base` (or at least boot libraries), we can easily generalise this function.

**Comment by josephcsible** [comment]
Can we change this to use `traverse` instead of `mapM`, so that it can support applicatives that aren't monads?

**Comment by chshersh** [comment]
@josephcsible Do you have a particular use case in mind?

**Comment by josephcsible** [comment]
Not offhand. I just ask because that's how `wither` is, and I can't think of a good reason to have a new function be less general than it could otherwise be.
