### ISSUE TITLE
Build with GHC-8.6.1

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#23]
No need to put on CI, but good to check locally at least.

**Comment by ChShersh** [comment]
Library builds with `ghc-8.6.1` but `tasty` fails to build.

**Comment by ChShersh** [comment]
I've tested again. It now builds. But `doctest` fails. Because something has changed in `base`.

**Comment by vrom911** [comment]
I can't make it work. It seems not possible to build `doctest` without `--allow-newer`. Do you really think that it's a sane idea to put `allow-newer`?

**Comment by ChShersh** [comment]
@vrom911 No, we're not going to build `relude` with `allow-newer`. It should be buildable without `allow-newer`. It's a pity that `doctest` doesn't build with `ghc-8.6.1` 😞

Maybe it makes sense to create issue in `doctest` to track the status of building with GHC-8.6.1.
Looks like build with `ghc-8.6.1` for `relude` is delayed for better times...

**Comment by ChShersh** [comment]
Tracking the status of the issue with `doctest` here:

* https://github.com/sol/doctest/issues/207

**Comment by vrom911** [comment]
Okay, the next stop is `stm`. Seems it's going to be released soon (?).
https://github.com/haskell/stm/issues/16

**Comment by vrom911** [comment]
Updates: the library is building now 🎉 
The problem now is tests, more accurate – `doctest` library. I've opened the PR in there, but it's very hard to say if it will be approved (and work).

**Comment by ChShersh** [comment]
@vrom911 Thanks for your effort! I hope that issue with `doctest` can be resolved soon... I would like to add support for GHC-8.6.1 to `relude` as soon as possible.
