### ISSUE TITLE
Generalized composition?

### ISSUE THREAD

**Issue by argantos** [kowainik/relude#231]
In some cases a generalized composition operator (like [this one](https://hackage.haskell.org/package/universum-1.6.0/docs/Universum-VarArg.html)) is very useful.

It would be nice to include something like this in relude (probably as an `Extra` module?).

**Comment by chshersh** [comment]
@argantos We had a generalised composition in `relude` before, but it was removed in version `0.1.0`. Polyvariadic functions are not standard in Haskell, type inference can be very bad sometimes, and error messages are poor. We decided that it's not worth it, and we want to focus more on beginner-friendliness. Also, benchmarks by @vrom911 confirmed that in some cases the performance of the `...` operator could be extremely slow. So it might not be a good idea to provide a tool which you can't just use without care. In the end, I want to add that I've been using `relude` in production for a couple of years, and I never had a need to use polyvariadic composition function. It wasn't a pain point for me.

**Comment by argantos** [comment]
Thanks for ur quick response, fair enough!
