### ISSUE TITLE
Safe path library

### ISSUE THREAD

**Issue by srid** [kowainik/relude#232]
Hello,

Any thoughts on having `Relude.File` use something like http://hackage.haskell.org/package/path instead of `FilePath`?

**Comment by chshersh** [comment]
Hi @srid, thanks for the proposal. But we don't have plans to depend on any of the filepath libraries. One of the `relude` goals is minimalism, specifically:

> We don't force users of relude to stick to some specific lens or text formatting or logging library.

Same goes for path libraries. There are multiple safe path libraries, and none of them is the de-facto standard in the Haskell world. We don't even expose pieces of the `filepath` and `directory` libraries which are boot libraries, for these particular reasons.
