### ISSUE TITLE
Relude.Lifted.Concurrent is awkward

### ISSUE THREAD

**Issue by mithrandi** [kowainik/relude#239]
Functions like `retry` and `newTMVar` are not reexported, but if you import `Control.Concurrent.STM` to get them then the lifted definitions of `atomically` etc. conflict with the regular ones.

**Comment by chshersh** [comment]
I don't mind reexporting `newTMVar`, this sounds useful. On the other hand, `retry` sounds like a too generic name to be exported by the prelude. 

To avoid conflicts and use `relude` alongside with other modules, you can use explicit imports:

```haskell
import Control.Monad.STM (retry)
```

**Comment by mithrandi** [comment]
What about `orElse`, `check`, `throwSTM`, and `catchSTM`?

**Comment by mithrandi** [comment]
Working on a PR.
