### ISSUE TITLE
Fix partiality in 'cycle'

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#256]
To my big surprise, the `cycle` function from `base` is partial: it fails on empty lists

```haskell
ghci> :t cycle
cycle :: [a] -> [a]
ghci> cycle []
*** Exception: Prelude.cycle: empty list
```

It's a bit problematic, since we don't want to expose partial functions. I see the following options:

1. Don't reexport `cycle`.
2. Change its type to `NonEmpty a -> NonEmpty a`.
3. Reimplement manually by returning empty list when empty list is given.

@vrom911, what do you think?

**Comment by vrom911** [comment]
I guess the less painful way would be to use the third option. And also this was my expectation of this function all along. I believe many people could expect such behaviour as well.

But in any case, this would be a breaking release. However, this is for the good :slightly_smiling_face:
