### ISSUE TITLE
Is there plans for an AUR repo?

### ISSUE THREAD

**Issue by selene57** [kowainik/relude#310]
Are there plans at all on adding this to an AUR repo for easy install (without unnecessarily dealing with additional package managers)?

Thanks!

**Comment by chshersh** [comment]
@selene57 I'm not using Arch personally, so there are no plans for doing so. Though, can you elaborate a bit on benefits for providing an AUR repo? In my understanding, Arch has its own package manager, and there's a sense in providing an easy way of installing applications or services using the OS package manager. But `relude` is a library, and it's supposed to be used during the development of other Haskell packages, e.g. when you build them with Cabal or Stack.
