### ISSUE TITLE
Reexport 'hFlush'

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#314]
And lift to `MonadIO`

**Comment by rektrex** [comment]
@chshersh, I would like to try to make the changes using the new module structure.

**Comment by chshersh** [comment]
@rektrex The idea is to create a separate module called `Relude.Lifted.Handle` and put lifted and specialized versions of useful `Handle`-related functions in there. The module has a lot of functions, and we can always expand reexports when necessary. But I think that the following functions are useful at the moment:

* `hFlush`
* `hIsEOF`
* `BufferMode`
* `hSetBuffering`
* `hGetBuffering`

Additionally, it would be nice to move the following `Handle` definitions from `Relude.Base` to the new module `Relude.Lifted.Handle` for the sake of consistency:

* `Handle`
* `stdin`
* `stdout`
* `stderr`
* `withFile` (note, that even if `withFile` function has `IO` in its type, we can't lift this function properly, so we just don't touch it and reexport as it is)

After that, we can reexport add `Relude.Lifted.Handle` from `Relude.Lifted`.

Adding HLint rules for all these functions would be great as well!

Also, adding `@since 0.8.0.0` annotations to the module and all new functions would be appreciated 🙂

**Comment by rektrex** [comment]
> Additionally, it would be nice to move the following Handle definitions from Relude.Base to the new module Relude.Lifted.Handle for the sake of consistency

Sorry, I don't understand this part.

I'll start with the other parts

**Comment by chshersh** [comment]
> Additionally, it would be nice to move the following Handle definitions from Relude.Base to the new module Relude.Lifted.Handle for the sake of consistency

@rektrex No worries! Sorry if I wasn't clear. What I mean is that the `Relude.Base` module currently exports `Handle`, `stdount` and other functions from that list. But since we are introducing a separate `Relude.Lifted.Handle` module, it makes sense to reexport everything related to handles from this module instead, to keep the API and code more consistent. So these old things that we already reexport from `Relude.Base` should be reexported from `Relude.Lifted.Handle` instead.
