### ISSUE TITLE
Document that mixins doesn't work with stack repl

### ISSUE THREAD

**Issue by rikvdkleij** [kowainik/relude#328]
Following those instructions https://kowainik.github.io/projects/relude#mixins  (also via summoner with Relude as alternative Prelude) Relude becomes not the default Prelude.

For some reason the GHC Prelude is not overridden/replaced by Relude.

**Comment by rikvdkleij** [comment]
I'm using macOS and stack 2.3.3

**Comment by chshersh** [comment]
Hi @rikvdkleij, could you provide a minimal example and your specific error? Most likely this is a Stack issue.

**Comment by rikvdkleij** [comment]
I have created the project with summoner cli by entering relude as alternative prelude.
The generated Cabal file looks okay:
```
common common-options
  build-depends:       base ^>= 4.13.0.0
                     , relude
  
  mixins:              base hiding (Prelude)
                     , relude (Relude as Prelude)
  
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-uni-patterns
                       -Wincomplete-record-updates
  if impl(ghc >= 8.0)
    ghc-options:       -Wredundant-constraints
  if impl(ghc >= 8.2)
    ghc-options:       -fhide-source-paths
  if impl(ghc >= 8.4)
    ghc-options:       -Wmissing-export-lists
                       -Wpartial-fields
  if impl(ghc >= 8.8)
    ghc-options:       -Wmissing-deriving-strategies

  default-language:    Haskell2010
  default-extensions:  OverloadedStrings

library
  import:              common-options
  hs-source-dirs:      src
  exposed-modules:     Testrelude
```

And when I created a module which imports nothing and I want to use e.g. `NonEmptyList` GHC says that's not in scope.

When I import Relude explicitly in module then GHC can find `NonEmptyList` but GHC gives error on e.g. `putStrLn` because of ambiguous occurences.

**Comment by vrom911** [comment]
I believe that you are encountering this Stack issue: https://github.com/commercialhaskell/stack/issues/5077

If it is not the case, please provide some more details on how you build the project when you get the error (it would be nice to see module as well and the command with the output 🙂 ).

**Comment by rikvdkleij** [comment]
Thanks, yes, it's the same issue. Maybe you can put a note in the documentation that the recommended way doesn't work (yet) with stack.

**Comment by vrom911** [comment]
Nice idea! I will add it into troubleshooting section of the README.
