### ISSUE TITLE
Any documentation to use it with Stack

### ISSUE THREAD

**Issue by sycured** [kowainik/relude#334]
I don't use cabal but stack.
Have you any documentation to use relude with stack?

**Comment by vrom911** [comment]
All the documentation provided can be used both with Cabal and Stack. Do you have any specific question of what you are having the issue with?

**Comment by sycured** [comment]
My question was more about that the mixins example is exclusively for Cabal.
Is it the same for stack.yml or package.yml?

It can be strange but I learned (continue to learn) exclusively with stack.

**Comment by vrom911** [comment]
All the relevant info is in the documentation already, including the Stack problem with GHCI. Nothing more we could help with here.

**Comment by sandydoo** [comment]
> My question was more about that the mixins example is exclusively for Cabal.
> Is it the same for stack.yml or package.yml?

Hey, @sycured, I initially had the same question.

`Stack` uses a format called [`hpack`](https://github.com/sol/hpack) to describe and configure packages — that’s your `package.yaml` file. The `.cabal` file is then automatically generated from that whenever you build the project.

[From the documentation](https://github.com/sol/hpack/blob/master/README.md#-dependencies), we can find out how the `cabal` examples map to `hpack`’s yaml format. For example, here’s how you would specify mixins:

> When a dependency is specified as an object, you can use the mixin field to control what modules from the dependency your program will see and how its signatures are filled in:
> ```yaml
>  dependencies:
>    # This gives you a shorter name to import from, and hides the other modules.
>    - name: containers
>      mixin:
>        - (Data.Map.Lazy as Map)
>    # This hides the System.IO.Unsafe module, and leaves the other modules unchanged.
>    - name: base
>      mixin:
>        - hiding (System.IO.Unsafe)
>    # This exposes only the listed modules - you won't be able to import the others!
>    - name: lens
>      mixin:
>        - (Control.Lens, Data.Set.Lens, Data.Map.Lens as MapL)
>    # This will rename the module, and expose the others.
>    - name: transformers
>      mixin:
>        - hiding (Control.Monad.Trans.State.Lazy)
>        - (Control.Monad.Trans.State.Lazy as State)
> ```

So to override `Prelude` using mixins, here’s how your `package.yaml` should look like:

```yaml
dependencies:
- name: base
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- name: relude
  mixin:
    - (Relude as Prelude)
```

Hope this helps! 😄

**Comment by sullyj3** [comment]
I found this pretty confusing as well, thanks for the info Sandy!
