### ISSUE TITLE
Dhall generated hlint error

### ISSUE THREAD

**Issue by adamConnerSax** [kowainik/relude#340]
I generated the ".hlint.yaml" file as instructed, via dhall-to-yaml (v. 1.7.4) and the resulting yaml caused an error when hlint (v. 3.2.1) tried to parse it:
```
hlint: user error (Failed to read YAML configuration file ~/DataScience/knit-haskell/.hlint.yaml
  Aeson exception:
Error in $: Error when decoding YAML, Expected a String
Along path: root 475 warn rhs
When at: Bool
warn:
  lhs: Data.Function.on
  note: '''on'' is already exported from Relude'
  name: Use 'on' from Relude
  rhs: true
)
```

This was "fixed" by adding double quotes around "on" on line 1796 of the .hlint.yaml.  No idea why.  Just guesswork from the error message.

**Comment by chshersh** [comment]
Hi @adamConnerSax! This is a known issue, and I reported it earlier to the `dhall-haskell` repository:

* https://github.com/dhall-lang/dhall-haskell/issues/1785

So, yeah, this is something that should be fixed on the Dhall side. But I also quoted this line manually to make it work. 

Maybe using a newer version of `dhall-to-yaml` tool can help with this?

**Comment by adamConnerSax** [comment]
Thanks!  I'll close this and use my hand-edited version until there's a new release of dhall-json.
