### ISSUE TITLE
Please, can relude Hackage provide links to the source

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#344]
I basically wanted to look at the advanced Haddock use you have in the `relude`.

And `relude` on Hackage has no links to the source code. Giving "Here, use this"/"Look, but do not touch" kind of feel.
Well, when it is convenient to hide the implementation from users...
If developers do not see the source - they more probably would drive-by like me without reading/participation in the code.
If the source code is seen on Hackage, you may receive an additional stream of developers with drive-by contributions or discussions, and as always - the more people engage with the source code - the more they are likely to stay.

**Comment by chshersh** [comment]
All `relude` source code on Hackage (including links to this repository and source codes for individual functions). If you don't like how Hackage renders that, I recommend you open an issue to Hackage or Haddock. As `relude` maintainers we are not in control of that.

**Comment by Anton-Latukha** [comment]
Yep, there seem source links in some modules.

When I looked yesterday in some main modules - there are none, like in https://hackage.haskell.org/package/relude-0.7.0.0/docs/Relude-Base.html

Ok, please do not be salty I just pinged you on a question.

Yep. Hackage *state* is an *issue*. I do not know for *the process*.

Thank you for a personal responce.
