### ISSUE TITLE
Support GHC-9.0

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#345]
- [ ] Update bounds
- [ ] Update CI
- [ ] Check if there's anything useful in `base-4.15` that we can export:
    * https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.0/libraries/base/changelog.md

**Comment by vrom911** [comment]
Blocked by https://github.com/hedgehogqa/haskell-hedgehog/issues/416 at the moment.
