### ISSUE TITLE
`foldr1` does not replace `Data.Foldable ( foldr1 )`

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#373]
`HNix` is a pretty big project. And the migration to `relude` went smooth, the migration took ~2d of work for everything, and also to debug this issue.

https://github.com/haskell-nix/hnix/blob/cd02c6dd59105ccbfb36218fba3b0bce3c8c77ad/src/Nix/Parser.hs#L607-L608
```haskell
manyUnaryOp :: MonadPlus f => f (a -> a) -> f (a -> a)
manyUnaryOp f = foldr1 (.) <$> some f
```
`Data.Foldable ( foldr1 )` would be:
![Screenshot-2021-03-21-21:03:30](https://user-images.githubusercontent.com/20933385/111917485-e9585e00-8a88-11eb-8a10-28a9fee8e593.png)

If we to use `relude` `foldr1` for that we would receive:
```
src/Nix/Parser.hs:609:32: error:
    • Couldn't match type ‘[a -> a]’ with ‘a0 -> b0’
      Expected type: f (a0 -> b0)
        Actual type: f [a -> a]
    • In the second argument of ‘(<$>)’, namely ‘some f’
      In the expression: foldr1 (.) <$> some f
      In an equation for ‘manyUnaryOp’:
          manyUnaryOp f = foldr1 (.) <$> some f
    • Relevant bindings include
        f :: f (a -> a) (bound at src/Nix/Parser.hs:609:13)
        manyUnaryOp :: f (a -> a) -> f (a -> a)
          (bound at src/Nix/Parser.hs:609:1)
    |
609 | manyUnaryOp f = foldr1 (.) <$> some f
    |                                ^^^^^^
```

![Screenshot-2021-03-21-21:04:43](https://user-images.githubusercontent.com/20933385/111917544-31778080-8a89-11eb-9e3a-438a3d3e4734.png)

This is the only thing that was on the Relude side during migration. At first, I've with GHC thought that is some Skolem Existential thing, because was looking from the Relude function side.

But then, nope, `Relude`s `foldr1` asks for a base case, while `Foldable` one is not.

**Comment by chshersh** [comment]
I mentioned some challenges in implementing `foldr1` in the following comment:

* https://github.com/kowainik/relude/issues/307#issuecomment-798973946

In short, changing the type would be nice but the implementation has some challenges and requires a major version bump up.

**Comment by Anton-Latukha** [comment]
Ok.
Considering this as seen, discussed and closed.
