### ISSUE TITLE
`.hlint` holds the `foldrM` rule, but `relude` does not provide `foldrM`

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#377]
Currently `foldrM` is [(nor reexported)](https://github.com/kowainik/relude/blob/main/src/Relude/Foldable/Reexport.hs) [(nor provided)](https://github.com/kowainik/relude/search?q=foldrM), so HLint rule:

https://github.com/kowainik/relude/blob/943b8864bae8c149c611b7e5629cf37289a99a25/.hlint.yaml#L1732-L1736

does not hold true.

**Comment by chshersh** [comment]
Thanks. Fixed in `main`.
