### ISSUE TITLE
How to use it with stack & hpack

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/relude#381]
`stack` uses `hpack` format for `package.yaml` file.

It is hard to find information on how to do mixins with `stack`, or with `hpack.

The only mention of a `stack` configuration in the ReadMe is a bug report with `stack repl`.

But how project works with `stack` & `hpack` in the first place at all?

**Comment by vrom911** [comment]
> It is hard to find information on how to do mixins with stack, or with `hpack.

The issue you describe is build-tool-specific and is not core to `relude`. The person using a non-standard format such as hpack instead of `.cabal` is taking the risk. We don't have the capacity to keep an eye at all the existing solutions and maintain way too much rather than standard ones.
