### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by chshersh** [kowainik/relude#388]

**Comment by chshersh** [comment]
Closed by #403

**Comment by kamek-pf** [comment]
Thanks for following up on this @chshersh, are you planning to release a new version on Hackage or are you waiting for other pull requests to be merged ?

**Comment by chshersh** [comment]
@kamek-pf We'll do the release when the time permits 🙂

**Comment by chris-martin** [comment]
Is there anything you need to help make the release?
