### ISSUE TITLE
Mixins: stack build error "Could not load module Relude.String, member of hidden package"

### ISSUE THREAD

**Issue by ulidtko** [kowainik/relude#393]
Hi @kowainik :pray:

Here I've minified a 4-file reproducer: [relude-mixins.zip](https://github.com/kowainik/relude/files/7690928/relude-mixins.zip)

On unpacking and `stack build` inside, this error appears:
```
foo> configure (lib)
Configuring foo-0.1.0.0...
foo> build (lib)
Preprocessing library for foo-0.1.0.0..
Building library for foo-0.1.0.0..
[1 of 2] Compiling Lib

/tmp/foo/src/Lib.hs:5:1: error:
    Could not load module ‘Relude.String’
    It is a member of the hidden package ‘relude-0.7.0.0’.
    Perhaps you need to add ‘relude’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Relude.String
  | ^^^^^^^^^^^^^^^^^^^^
```
And of course, build-depends in the cabal file contains exactly `relude ==0.7.0.0`.

Stack `Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f`. Not sure if commercialhaskell/stack#5077 is related; perhaps it is. The `--cabal-verbose` commandline looks sane too; could be even bug in Cabal or further below :man_shrugging: Reporting to Relude for definiteness.

As a workaround, I'm switching to `NoImplicitPrelude` + `import Relude`. That way gives me the `Text` reexport, without further fiddling with dependencies.

HTH

**Comment by chshersh** [comment]
@ulidtko Yes, that mentioned Stack issue is the reason why `stack` doesn't work when the mixins approach is used. This is already documented in the README as per the relevant issue:

* #328 
* https://github.com/kowainik/relude#mixins
