### ISSUE TITLE
Support `hashable-1.4`?

### ISSUE THREAD

**Issue by kindaro** [kowainik/relude#394]
Currently, the bounds for `hashable` look like this: `hashable (>=1.2 && <1.4)`. But `hashable-1.4` already has two minor versions. Maybe the upper bound can be raised to include them?

**Comment by Anton-Latukha** [comment]
This broke the downstream project CI:

```
[__2] skipping: hashable-1.4.0.1, hashable-1.4.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=1.2 && <1.4' from 'relude')
[__2] trying: hashable-1.3.5.0
[__3] next goal: base (dependency of hnix)
[__3] rejecting: base-4.15.1.0/installed-4.15.1.0 (conflict: hashable =>
ghc-bignum>=1.0 && <1.1 || >=1.2 && <1.3, base =>
ghc-bignum==1.1/installed-1.1)
```

And the `v2-freeze` or `v2-test` do not allow `--allow-newer` to circumvent this.

To solve this downstream the downstream project/CI workflows would need to be redesigned to have `.project` to freeze on some Hackage `index-state` to circumvent this & pretend to live in the old Hackage state & that would mean to update `index-state` all the time on any update.

**Comment by Anton-Latukha** [comment]
Upload of `ghc-bignum 1.1` was requested at https://gitlab.haskell.org/ghc/ghc/-/issues/19632#note_400751.

**Comment by Anton-Latukha** [comment]
Several things happened in upstream packages to solve this, seems like upstream things should be resolved now.

`relude` can upgrade to new `hashable`.
