### ISSUE TITLE
General type conversion API

### ISSUE THREAD

**Issue by kamek-pf** [kowainik/relude#395]
Hey,

This is more of an open question and I realize it may go against the goals of this library, but have you considered offering a more general type conversion API as a part of Relude ?

I find [`witch`](https://hackage.haskell.org/package/witch-0.3.4.1/docs/Witch.html) does a pretty good job, an interface such as this one could replace the string conversion utility defined in Relude.String.Conversion and provide a general typeclass for common type conversion.

Curious to hear your thoughts about this.
And thank you for all your work on Relude, I really enjoy the library :)

**Comment by chshersh** [comment]
Hi @kamek-pf 👋🏻 

We don't have plans to introduce new abstractions in `relude`. One of the Relude goals is not to have too many custom typeclasses. The `ToText/...` typeclasses are just a very convenient and efficient way to convert between different string types.

We also have a goal to depend only on boot libraries and `witch` is not one of them. However, it's a pretty nice library 🙂 I never used it by myself but I like the interface and I appreciate the documentation 💯 

I would most likely use `witch` when I need lots of conversion utilities in my projects but there're other libraries out there and we don't want to enforce one approach over another in Relude.

Thanks for your kind words about our project 🤗
