### ISSUE TITLE
Relude re-exports unsafe IsList instance of NonEmpty

### ISSUE THREAD

**Issue by jhrcek** [kowainik/relude#402]
Thank you for working on this package, I'm very happy with it.

I just thought I'd flag this issue, since the package claims to be hiding partial functions by default.
Feel free to close this if there's nothing that should be done about this.

```bashx
$ stack ghci --package relude --ghc-options="-XNoImplicitPrelude"
relude> using precompiled package
     
      You are using snapshot: lts-18.27
     
Configuring GHCi with the following packages: 
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
λ> import Relude
λ> fromList [] :: NonEmpty ()
*** Exception: NonEmpty.fromList: empty list
```

This is how the instance looks in base:
https://hackage.haskell.org/package/base-4.15.0.0/docs/src/GHC-Exts.html#instance%20IsList%20(NonEmpty%20a)

**Comment by chshersh** [comment]
Hi @jhrcek 👋🏻 

Unfortunately, Haskell doesn't provide a way to not reexport specific instances 😞 The only options are either not to reexport `IsList` entirely or `NonEmpty` entirely. Both seem to restrictive so we're stuck here.

To avoid partial usages of `fromList` for `NonEmpty` I can recommend using [Stan](https://github.com/kowainik/stan). This Haskell static analyzer has an inspection to check for usages of `fromList` specifically for `NonEmpty`:

* https://github.com/kowainik/stan/wiki/All-Inspections#stan-0020
