### ISSUE TITLE
Cannot see any documentation

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [kowainik/relude#456]
The only function that has any docs is "when", the others have none
![image](https://github.com/kowainik/relude/assets/74532770/03a64f49-46b4-4776-8d0a-323dfada4fb1)
![image](https://github.com/kowainik/relude/assets/74532770/def0e6af-b44a-4aa4-9845-09d37c7fc07e)

So, I guess "when" comes from the original prelude while the others come from relude
Why I do not see the docs? Are there any at all?

**Comment by ildar-shaymukhametov** [comment]
![image](https://github.com/kowainik/relude/assets/74532770/9f9fb9c0-8abc-4e28-92ef-c6b963307412)
Generated using "stack haddock relude"
Same issue, do not see anything in editor

**Comment by tomjaguarpaw** [comment]
Perhaps someone from the Relude community has a suggestion.

**Comment by ildar-shaymukhametov** [comment]
Is there discord?

**Comment by tomjaguarpaw** [comment]
Not as far as I know.

**Comment by ildar-shaymukhametov** [comment]
Solved by -haddock ghc-option
