### ISSUE TITLE
Add <&>

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#48]
This operator is very useful often.

```haskell
infixl 1 <&>
(<&>) :: Functor f => f a -> (a -> b) -> f b`
```

**Comment by ghallak** [comment]
@ChShersh Is this going to be different from the already available [`(<&>)`](https://www.stackage.org/haddock/lts-12.5/base-4.11.1.0/Data-Functor.html#v:-60--38--62-), or do you mean it should just be re-exported?

**Comment by ChShersh** [comment]
@ghallak It should be the same as `<&>` from `base`. But this operator was introduced in `base` only in `GHC 8.4.1` while we would like it to have it in `relude` until `8.0.2` version. So some CPP magic should be involved.
