### ISSUE TITLE
Add `flap` operator

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#59]
This one:

```haskell
(??) :: Functor f => f (a -> b) - a -> f b
```

**Comment by vrom911** [comment]
I've never seen this function before and I can't find this function anywhere, can you tell why it's needed? And why you need to make an operator? Should I implement the function first?

**Comment by ChShersh** [comment]
@vrom911 These are good points. We can have both `flap` and `??` operator available. I learned about this operator from this document:

* https://github.com/zudov/24-days-of-syntactic-witchery#day-5--ff--a-

For me it's mostly useful when I have a list of function and want to apply them to single element, like this:

```haskell
ghci> [(+2), (*3)] ?? 5
[7, 15]
```

Or apply to function inside `Maybe`:

```haskell
ghci> Just (+3) ?? 5
Just 8
```

I can't say that this operator is as useful as other common operators like `<$>`, `<*>`, `<&>`, etc. But some people like it, and it's still useful sometimes.

In the document I've send in this comment, this operator is called `<@>` but in Haskell world it's more popular under `??` name from `lens` library:

* https://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-Lens.html#v:-63--63-
