### ISSUE TITLE
Reexport `Contravariant` for GHC >= 8.6.1

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#70]

**Comment by kahlil29** [comment]
Is this a complex issue? Any pointers as to how I can go about or start working on this?

**Comment by ChShersh** [comment]
@kahlil29 The issue it quite straightforward. You only need to export some parts of this module:

* http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Functor-Contravariant.html

And the reexport can go into `Relude.Functor.Reexport` module:

* https://github.com/kowainik/relude/blob/master/src/Relude/Functor/Reexport.hs

There're only extra parts you need to do:

1. Use `-XCPP` extension to export those functions only for when `base >= 4.12.0` (GHC 8.6.1)
2. Most difficult part: what to export and what not to export. Maybe exporting everything is okay. Need only to check, how popular are the names on Hackage with the same names.

**Comment by kahlil29** [comment]
@ChShersh Sorry, I somehow missed this reply earlier, will work on this and submit a PR by today 👍
