### ISSUE TITLE
Add HLint rules for `asumMap` function

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#86]
The `asumMap` function was recently introduced in #85:

https://github.com/kowainik/relude/blob/f69d531eafb7f397fa3103e9b811bd8f965a9108/src/Relude/Foldable/Fold.hs#L84-L85

It would be also great to add HLint rules for this function. I think it should be possible to come up with at least 3 different rules.

**Comment by cronokirby** [comment]
The only general thing I can think of atm is `asumMap f []` being `empty` otherwise there's specific things like `asumMap pure lst :: [a] = id` and `asumMap pure lst :: Maybe a` being a total version of head.

**Comment by ChShersh** [comment]
@cronokirby I think the following rules should be valid:

1. The implementation of `asumMap` (people might use their own `foldMap` with `Alt`)
2. Something like `foldr (\x acc -> f x <|> acc) empty`. This looks like another valid implementation of `asumMap`
3. And, of course: `asum (map f xs)`
