### ISSUE TITLE
Add `typeName` function to `Relude.Extra.Typeable` module

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#89]
The following function is very useful:

```haskell
typeName :: forall a . Typeable a => Text
```

I'm tired of copy-pasting it in every my project. So I think it's a good idea to implement it directly in `relude`.

**Comment by cronokirby** [comment]
Should we create a new module `Relude.Extra.Typeable` to put this in then?

**Comment by cronokirby** [comment]
In terms of the implementation, is there a better way of getting a text from the `ShowS` you get from `Typeable.showsTypeRep` other than `pack . ($ "")`

**Comment by ChShersh** [comment]
@cronokirby 

> Should we create a new module Relude.Extra.Typeable to put this in then?

Well, it definitely should go in some `Extra` module because `typeName` is very popular and for alternative prelude we usually don't want to spoil global namespace with conflicting names. And I can't think of better name... There's no such module among existing modules where we can put `typeName`, so, yeah, guess we need to create separate module. Another idea: we can call it `Relude.Extra.Type` to put all type-related functionality there.

> is there a better way of getting a text from the ShowS

You can just use `show` on `TypeRep` to show, it will do the trick :+1:
