### ISSUE TITLE
Add `hPut*` function to output directly to `Handle`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#91]
It would be really great to add lifted version of the following functions to the `Relude.Lifted.File` module:

* `hPutStr`
* `hPutStrLn`
* `hPrint`

They are here:

* https://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:hPutStr

The same should be done for `Text`, `LText`, `ByteString` and `LByteString` data types in the the `Relude.Print` module. So the following functions can be added:

* `Text`: `hPutText`, `hPutTextLn`
* `LText`: `hPutLText`, `hPutLTextLn`
* `ByteString`: `hPutBS`, `hPutBSLn`
* `LByteString`: `hPutLBS`, `hPutLBSLn`

**Comment by vrom911** [comment]
Is this used very often you'd like to have it in here? Do you want a separate module for this? These changes are huge, and it's also 200lines of `hlint`, should one add them or not?

**Comment by ChShersh** [comment]
@vrom911 Hmm, I didn't think about possible `.hlint.yaml` blow up 🤔 Yep, this can be a potential problem. 

These functions might be useful if you want to open file only once and then write to handle instead of creating `Handle` each time. Speaking of what, if you want to do this, you probably also want to use some logging library. For example, in `co-log` we have the following CPS-like functions to safely write to the file `Handle`:

* https://github.com/kowainik/co-log/blob/1942dc91a0ba0fe2cbaddc676c8d81bf8683db3b/co-log/src/Colog/Actions.hs

Although these functions are in `base` (for `String` type only) and it's probably a good idea to reexport common stuff from `base` if the names are unambiguous and already commonly used, the `.hlint.yaml` size growth really concerns me (and I didn't think about it earlier). It's extremely difficult to support in HLint functions for multiple string types so the threshold for introducing such functions into `relude` should be high enough as I see now. So I think we can keep the issue open just in case somebody extremely wants these functions and can come up with better motivation.
