### ISSUE TITLE
Add `&&^` and `||^` operators

### ISSUE THREAD

**Issue by ChShersh** [kowainik/relude#97]
They are often useful. Also, they are somewhat common because names are unambiguous. 

```haskell
(&&^) :: Monad m => m Bool -> m Bool -> m Bool
(||^) :: Monad m => m Bool -> m Bool -> m Bool
```

**Comment by mukul2gautam** [comment]
(&&^) : : monad m => m Bool -> m Bool -> m Bool
(||^) : : monad m => m Bool -> m Bool -> m Bool

**Comment by kahlil29** [comment]
Is this about using binding in a do notation and then getting the inner Bool values, applying the operator on it and then using `pure` again to return the final answer? 

Or is there more to it?

**Comment by ChShersh** [comment]
@kahlil29 I think you can also use `ifM` function for that:

https://github.com/kowainik/relude/blob/7506ab5b54d559b6cef8a75eeecd46095e795cd7/src/Relude/Bool/Guard.hs#L57-L58

**Comment by kahlil29** [comment]
Thanks @ChShersh I'll have a crack at it, then I'll ask for some feedback 😄

**Comment by cronokirby** [comment]
Why have `Monad` here instead of Applicative?

**Comment by ChShersh** [comment]
@cronokirby You can't achieve the following behavior with `Applicative`:

```haskell
ghci> Just False &&^ undefined
Just False
```

Monadic version is lazier.
